#!/bin/bash
RANK=$1
shift
HOSTFILE_CONTENT=${HOSTFILE_CONTENT:?set HOSTFILE_CONTENT JSON, e.g. '[[\"host-a:5005\"],[\"host-b:5005\"],[\"host-c:5005\"]]'}
TMPFILE=$(mktemp)
echo "$HOSTFILE_CONTENT" > $TMPFILE
export MLX_HOSTFILE=$TMPFILE
export MLX_RANK=$RANK
REMOTE_CLUSTER_DIR=${ODYSSEUS_REMOTE_CLUSTER_DIR:-$HOME/mlx-cluster}
PYTHON_REMOTE=${ODYSSEUS_PYTHON_REMOTE:-$REMOTE_CLUSTER_DIR/.venv/bin/python}
cd "$REMOTE_CLUSTER_DIR"
exec "$PYTHON_REMOTE" "$REMOTE_CLUSTER_DIR/inference_pipe.py" "$@"
