#!/bin/bash
RANK=$1
shift
COORDINATOR_IP=${COORDINATOR_IP:?set COORDINATOR_IP to the rank-0 host}
COORDINATOR_PORT=${COORDINATOR_PORT:-5005}
IBV_DEVICES=${IBV_DEVICES:?set IBV_DEVICES JSON matrix for this topology}
TMPFILE=$(mktemp)
echo "$IBV_DEVICES" > $TMPFILE
export MLX_IBV_DEVICES=$TMPFILE
export MLX_JACCL_COORDINATOR=${COORDINATOR_IP}:${COORDINATOR_PORT}
export MLX_RANK=$RANK
REMOTE_CLUSTER_DIR=${ODYSSAI_X_REMOTE_CLUSTER_DIR:-${ODYSSEUS_REMOTE_CLUSTER_DIR:-$HOME/mlx-cluster}}
PYTHON_REMOTE=${ODYSSAI_X_PYTHON_REMOTE:-${ODYSSEUS_PYTHON_REMOTE:-$REMOTE_CLUSTER_DIR/.venv/bin/python}}
cd "$REMOTE_CLUSTER_DIR"
exec "$PYTHON_REMOTE" "$REMOTE_CLUSTER_DIR/inference.py" "$@"
